### ISSUE TITLE
Unable to deploy this package on DUBBD v0.15.0

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-sso#38]
When updating my version of DUBBD to v0.15.0 this package fails to deploy. Here's the CI log: https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/actions/runs/7215006548/job/19658367257#step:4:17088

**Comment by RothAndrew** [comment]
Here's a simplified PR that is just updating DUBBD, nothing else: https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/pull/55

CI log: https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/actions/runs/7226491069/job/19692190419#step:4:17078

**Comment by rjferguson21** [comment]
It looks like this is an issue with Pepr violating [a newly enforced Kyverno policy](https://repo1.dso.mil/big-bang/bigbang/-/blame/master/chart/templates/kyverno-policies/values.yaml#L295). 

Pepr core should be setting a more explicit `securityContext`; I've created an issue [here](https://github.com/defenseunicorns/pepr/issues/444).

If you need an immediate workaround you can add an exclusion for that policy via DUBBD overrides:

```
kyvernoPolicies:
  values:
    policies:
      require-non-root-user:
        exclude:
          any:
            - resources:
                namespaces:
                  - pepr-system
```
